/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.stream.FileImageInputStream;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;

/**
 *
 * @author VégiDánielMárk(SZF_2
 */
public class Config extends javax.swing.JFrame {

    /**
     * Creates new form Config
     */
    public Config() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg_nyelv = new javax.swing.ButtonGroup();
        jFileChooser2 = new javax.swing.JFileChooser();
        jcmb_szakvalasztas = new javax.swing.JComboBox<>();
        jcb_hl = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jrb_j = new javax.swing.JRadioButton();
        jrb_js = new javax.swing.JRadioButton();
        jrb_php = new javax.swing.JRadioButton();
        jbt_reset = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_betolt = new javax.swing.JMenuItem();
        jmi_mentes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmi_kilepes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcmb_szakvalasztas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Szak kivalasztas --", "Szoftver programozas", "Hardver" }));

        jcb_hl.setText("Hirlevel");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nyelv\n"));

        btg_nyelv.add(jrb_j);
        jrb_j.setText("Java");

        btg_nyelv.add(jrb_js);
        jrb_js.setText("JavaScript");

        btg_nyelv.add(jrb_php);
        jrb_php.setText("PHP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_j)
                    .addComponent(jrb_js)
                    .addComponent(jrb_php))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrb_j)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_js)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_php)
                .addContainerGap())
        );

        jbt_reset.setText("-- Reset --");
        jbt_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_resetActionPerformed(evt);
            }
        });

        jMenu1.setText("Config");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmi_betolt.setText("Betoltes");
        jmi_betolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_betoltActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_betolt);

        jmi_mentes.setText("Mentes");
        jmi_mentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mentesActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_mentes);
        jMenu1.add(jSeparator1);

        jmi_kilepes.setText("Kilepes");
        jmi_kilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_kilepesActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_kilepes);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcmb_szakvalasztas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcb_hl)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbt_reset)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jcmb_szakvalasztas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcb_hl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_reset))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_resetActionPerformed
        jcmb_szakvalasztas.setSelectedIndex(0);
        jcb_hl.setSelected(false);
        btg_nyelv.clearSelection();
    }//GEN-LAST:event_jbt_resetActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jmi_mentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mentesActionPerformed
        String ki = jcb_hl.isSelected() + "";

        JFileChooser fch = new JFileChooser();
        int v = fch.showSaveDialog(rootPane);
        if (v == JFileChooser.APPROVE_OPTION) {
            File f = fch.getSelectedFile();
            String fn = f.getAbsolutePath();

            FileOutputStream fajlKi = null;

            try {
                fajlKi = new FileOutputStream(f);
                ObjectOutputStream objKi = new ObjectOutputStream(fajlKi);
                objKi.writeObject(jcb_hl);
                objKi.writeObject(jcmb_szakvalasztas);
                objKi.close();
            } catch(FileNotFoundException ex) {
                Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
            } catch(IOException ex){
                Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

//        String ki = jcb_hl.isSelected() + "";
//        try {
//            Files.write(Paths.get("hirlevelKer.txt"), ki.getBytes());
//            System.out.println("file ki siker");
//        } catch (IOException ex) {
//            Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
//        }

    }//GEN-LAST:event_jmi_mentesActionPerformed

    private void jmi_kilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_kilepesActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmi_kilepesActionPerformed

    private void jmi_betoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_betoltActionPerformed
        JFileChooser fch = new JFileChooser();
        int v = fch.showSaveDialog(rootPane);
        if (v == JFileChooser.APPROVE_OPTION) {
            File f = fch.getSelectedFile();
            String fn = f.getAbsolutePath();

            FileInputStream fajlBe = null;

            try {
                fajlBe = new FileInputStream(f);
                ObjectInputStream objBe = new ObjectInputStream(fajlBe);
                JCheckBox jcb = (JCheckBox)objBe.readObject();
                jcb_hl.setSelected(jcb.isSelected());
                objBe.readObject();
                objBe.close();
            } catch(FileNotFoundException ex) {
                Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
            } catch(IOException ex){
                Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jmi_betoltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg_nyelv;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jbt_reset;
    private javax.swing.JCheckBox jcb_hl;
    private javax.swing.JComboBox<String> jcmb_szakvalasztas;
    private javax.swing.JMenuItem jmi_betolt;
    private javax.swing.JMenuItem jmi_kilepes;
    private javax.swing.JMenuItem jmi_mentes;
    private javax.swing.JRadioButton jrb_j;
    private javax.swing.JRadioButton jrb_js;
    private javax.swing.JRadioButton jrb_php;
    // End of variables declaration//GEN-END:variables
}
